### ISSUE TITLE
Added files are not committed

### ISSUE THREAD

**Issue by brsanthu** [olamy/maven-scm-provider-jgit#2]
I'm using the Maven Scm API in java embedded app and using JGit maven scm provider. New files are added using add command but when I check in, those files are not committed and pushed upstream.

Was trying to debug, and found that there is an issues with path comparison in JGitUtils.java file.

```
String path = relativize( baseUri, itfl.next() );
if ( path.equals( scmfile.getPath() ) )
{
    addedFiles.add( scmfile );
}
```

The value of path and value returned by scmFile.getPath uses different path separator and hence equals comparison fails, and hence skips the commit process.

Path needs to be normalized before comparing.

**Comment by olamy** [comment]
project moved as part of maven-scm see https://github.com/apache/maven-scm
